### ISSUE TITLE
My Hubot has amnesia 

### ISSUE THREAD

**Issue by kevinkuszyk** [bfcamara/hubot-azure-scripts#4]
I have the Azure blob brain wired up in my Hubot and it's working well.  However sometimes the custom attributes I've added to users are wiped out.  It's like something is resetting or writing an vanilla copy of the brain to blob storage.

Have you seen this before?  And any ideas how to fix it?

**Comment by bfcamara** [comment]
Oh that's bad. I've never seen this before. Is it something that you can repro, or is it happening randomly. The custom attributes are being wiped out for all customers or for just a few? Any chance that you have any other process writing on the same blob?

I was now looking at the code to find out how a condition in which this issue can happen. When I am writing the blob I am not using any options to control the access conditions.

https://msdn.microsoft.com/en-us/library/dd179371.aspx

Do you have multiple hubot instances running and targeting the same container? I can imagine a race condition where Hubot1 reads blob Data0, Hubot reads blob Data0 as well, Hubot 1 writes Data1 and then when Hubot2 is goint to write its Data2 it will destroy Data1.

**Comment by kevinkuszyk** [comment]
I haven't been able to consistently repro it yet, but it seems to be happening when I make a webhook call to my Hubot.

I only have one instance running at a time, so I don't think I'm seeing the race condition.    I'll keep an eye on it this week and post an update when I have some more information.

**Comment by kevinkuszyk** [comment]
I think I've found the solution.  The brain seems to be reset when I change rooms.  We're using the Rocket.Chat adapter, so I'll open an issue their repro.
